# Generated by Django 5.2.17 on 2026-08-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_path', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('competition', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('home_goals', models.PositiveIntegerField(blank=True, null=True)),
                ('away_goals', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='core.club')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('current_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_players', to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('penalty_goals', models.PositiveIntegerField(default=0)),
                ('penalty_attempts', models.PositiveIntegerField(default=0)),
                ('shots', models.PositiveIntegerField(default=0)),
                ('shots_on_target', models.PositiveIntegerField(default=0)),
                ('passes_completed', models.PositiveIntegerField(blank=True, null=True)),
                ('passes_attempted', models.PositiveIntegerField(blank=True, null=True)),
                ('key_passes', models.PositiveIntegerField(blank=True, null=True)),
                ('crosses', models.PositiveIntegerField(default=0)),
                ('dribbles_completed', models.PositiveIntegerField(blank=True, null=True)),
                ('dribbles_attempted', models.PositiveIntegerField(blank=True, null=True)),
                ('tackles_won', models.PositiveIntegerField(default=0)),
                ('interceptions', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('fouls_committed', models.PositiveIntegerField(default=0)),
                ('fouls_drawn', models.PositiveIntegerField(default=0)),
                ('offsides', models.PositiveIntegerField(default=0)),
                ('own_goals', models.PositiveIntegerField(default=0)),
                ('penalty_won', models.PositiveIntegerField(default=0)),
                ('penalty_conceded', models.PositiveIntegerField(default=0)),
                ('shots_faced', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('penalty_faced', models.PositiveIntegerField(default=0)),
                ('penalty_saved', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_statistics', to='core.club')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='core.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('actual_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prediction_error', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EVALUATED', 'Evaluated')], default='PENDING', max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('season', 'match_date', 'home_club', 'away_club'), name='unique_match_per_season'),
        ),
        migrations.AddConstraint(
            model_name='playerstatistics',
            constraint=models.UniqueConstraint(fields=('player', 'match'), name='unique_player_statistics_per_match'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.UniqueConstraint(fields=('player', 'match'), name='unique_prediction_per_player_match'),
        ),
    ]
