# Generated by Django 5.2.17 on 2026-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_club_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistics',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
