# Generated by Django 5.2.17 on 2026-09-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_playerstatistics_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Both', 'Both')], default='Right', max_length=5),
        ),
    ]
